### PR TITLE
Add hints to error messages and catch errors earlier

### PR DESCRIPTION
**Pull request by bendudson**
Helped in finding issues for a double null case

- [ ] Closes #xxxx
- [ ] Tests added
- [ ] Updated `doc/whats-new.md` with a summary of the changes

### CODE REVIEW

**Review by johnomotani — APPROVED** [review]
Thanks @bendudson! Looks good to me. I've also added one more suggestion about increasing spacing to deal with a negative gradient.

**Comment by bendudson** [comment]
Thanks @johnomotani ! Has Black changed? When I apply black version 21.10b0 to these files I get lots of changes (e.g. adds spaces around `**` operators).

I'd like to further automate grid generation, so am wondering if there is a way that we can annotate these error messages so that an automatic script could understand these hints Rather than writing a custom parser, perhaps a list of things to try in JSON format 
```
[{'psinorm_sol_inner':'increase'},
 {'poloidal_spacing_method':'monotonic'}]
```
might hint that the caller should either increase `psinorm_sol_inner` or set `poloidal_spacing_method` to 'monotonic'.

**Comment by ZedThree** [comment]
Yep, that changed in [22.1.0](https://black.readthedocs.io/en/stable/change_log.html#id34) -- lots of people complained about `x**2` being changed to `x ** 2`! I think it still keeps the spaces if `x` is not just a literal or simple variable

**Comment by johnomotani** [comment]
@bendudson further automated grid generation would be awesome! I'm totally in favour of parse-able hints. If it's doable, maybe YAML formatted strings instead of JSON, since we already use a YAML parser?

I think it might be tricky to do though (in some cases at least). The place where the error occurs is several levels down from where the option is read, as for example a 'spacing function' could be used where the target spacing is any of `target_inner_lower_poloidal_spacing_length`, `target_inner_upper_poloidal_spacing_length`, `target_outer_upper_poloidal_spacing_length`, or `target_outer_lower_poloidal_spacing_length` (or possibly various nonorthogonal variants?). You'd have to somehow keep track of which option had been passed in to the function that eventually fails, possibly through several other functions. [The 'spacing functions' are a bit spaghetti-like at the moment and could really do with a good refactor, which might make this easier...]

Having said that, maybe an option would be something like: rather than passing the value of a parameter, pass the name. Then when the value is actually used, it could just be retrieved from the options there, and the low-level function would know both which setting it was and the value.

**Pull request merged**
