### PR TITLE
Catch RuntimeError when calling git diff

### PR DESCRIPTION
**Pull request by bendudson**
If using a 'dirty' installation, running scripts from outside the repository can fail. This catches these errors.

- [ ] Closes #xxxx
- [ ] Tests added
- [ ] Udated manual
- [ ] Updated `doc/whats-new.md` with a summary of the changes

### CODE REVIEW

**Comment by johnomotani** [comment]
Hi @bendudson - how do you get the error that is being caught in this PR? I can't quickly reproduce, and I'd have hoped it would never happen!

**Comment by bendudson** [comment]
Hi @johnomotani ! I made an edit to the code, then without committing it ran `pip install --user .` to install it (so hit the "dirty" branch). Running `hypnotoad-gui` from within the git repository works, but changing to another directory and running it produced a runtime error from git complaining that it wasn't in a git repository.

**Comment by johnomotani** [comment]
@bendudson - ah, I see now! The recommended solution would be to do an editable install `pip install --user -e .`, which also has the advantage that changes to the source are immediately reflected in `hypnotoad-gui`, etc.

I'll have a think about this - my feeling is that we need a documentation fix (and possibly a better error message), to say only use `pip -e` for installs from source. It's nice to make sure the provenance-tracking information is always there, or in cases like this where it would mess up an error is thrown.

**Comment by bendudson** [comment]
Thanks @johnomotani I'd not known about (or forgotten) the `-e` option. Very handy!

**Pull request closed without merging**
