### PR TITLE
Output poloidal coordinates

### LINKED ISSUE #49: Definition of dy in the core
Following discussion with H.Seto, it would be useful for post-processing if dy was defined so that y went from 0 to 2pi in the core region of tokamak grids. Is there a way to do this, while allowing for cases like Torpex where there isn't a core region?

### PR DESCRIPTION
**Pull request by johnomotani**
Define `y`, `theta` and `chi` coordinates for output from `BoutMesh`.
- `y` increments by `dy` between points and starts from zero at the beginning of the global grid. `y` includes boundary cells and is single-valued (at a given radial position) everywhere on the global grid. `y` has branch cuts adjacent to both X-points in the core, and adjacent to the X-point in the PFRs.
- `theta` increments by `dy` between points and goes from 0 to 2pi in the core region. The lower inner divertor leg has negative values. The lower outer divertor leg has values >2pi. The upper inner leg (if it exists) has values increasing continuously from those in the inner SOL (these will overlap values in the outer core region). The outer upper leg (if it exists) has values continuous with those in the outer SOL (these will overlap values in the inner core region).
- `chi` is a straight-field line poloidal coordinate proportional to the toroidal angle (i.e. to zShift). It goes from 0 to 2pi in the core, and is undefined on open field lines.

Also includes fix for bug that meant `ShiftAngle` got written as all-`nan` even when there is a core region.

- [x] Closes #49 
- [x] Updated `doc/whats-new.md` with a summary of the changes

### CODE REVIEW

**Comment by johnomotani** [comment]
Note that because (https://github.com/boutproject/hypnotoad/issues/49#issuecomment-651073736)
> Apparently the old hypnotoad is also 0 -> 2pi in ny, not in the core

After this PR, dy and various metric coeffiecients, etc. will be rescaled significantly compared to the original hypnotoad (currently smaller difference are just due to slightly differently chosen grid-point positions or accuracy of interpolations, etc.). If `f = ny_core/ny` is the rescaling factor:
* `dy = f*dy_old`
* `hy = hthe_old/f`
* `J = J_old/f`
* `g22 = g22_old*f**2`
* `g12 = g12_old*f`
* `g23 = g23_old*f`
* `g_22 = g_22_old/f**2`
* `g_12 = g_12_old/f`
* `g_23 = g_23_old/f`
* `curl_bOverB_y = curl_bOverB_y_old*f`

**Comment by ZedThree** [comment]
Very possibly a stupid question, but does that end up changing the physical size of the domain?

**Comment by johnomotani** [comment]
No, I'm pretty sure (I read through all the places `dy` and `hy` are used) that it doesn't change the physical size of the grid. The scaling of the `y` coordinate was just an arbitrary choice in the first place, and everywhere it is used the rescaling here should cancel out - e.g. `Grad_par(A) = DDY(A)/sqrt(g_22) = index_DDY(A)/dy/sqrt(g_22)` and so the scaling factor `f` that I defined in my previous comment cancels between `dy` and `sqrt(g_22)`.

**Comment by bendudson** [comment]
I think this is right; `y` is an arbitrary choice of coordinate. The physical poloidal distance `lpol` is related to `dy` by the scale factor `hthe`. As long as `hthe * dy` is constant then the physical size of the grid is unchanged.

**Comment by johnomotani** [comment]
Now calculates `chi` as a straight-field-line poloidal coordinate, as discussed in #49.

Also fixes a bug that meant `ShiftAngle` was written as all-`nan` even when a core region is present.

**Review by bendudson — APPROVED** [review]

**Pull request merged**
